name: Main

on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main
    tags:
      - "**"
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: nightly
      - uses: actions/checkout@v2
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v2
      - run: cargo clippy --all-targets -- -D clippy::all

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - run: cargo check --all

  test:
    needs: [codestyle, lint, compile]
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest

    # we care mostly about stable but want visibility on beta and nightly
    continue-on-error: ${{ matrix.rust != 'stable' }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test
